# Generated by Django 3.1.4 on 2021-05-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210527_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
