# Generated by Django 3.1.4 on 2021-05-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210528_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item',
            new_name='items',
        ),
    ]
