# Generated by Django 3.1.4 on 2021-06-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('items', '0012_auto_20210604_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
