# Generated by Django 3.1.4 on 2021-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
