# Generated by Django 3.1.4 on 2021-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210604_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='items.ItemImage'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shops',
            field=models.ManyToManyField(blank=True, null=True, to='items.Shop'),
        ),
    ]
