# Generated by Django 3.1.4 on 2021-06-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210604_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='items',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
