# Generated by Django 3.1.4 on 2021-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20210608_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
