# Generated by Django 3.1.4 on 2021-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_item_is_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
