# Generated by Django 3.1.4 on 2020-12-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'moderator'), ('3', 'user')], default='user', max_length=20),
        ),
    ]
